name: Build and Push backend Service to ACR

on:
  push:
    paths:
      - "backend/**"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-push-backend-service:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set Tag as Environment Variable
        run: echo "IMAGE_TAG=$(date +'%Y%m%d')-${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/backend-service:${IMAGE_TAG} ./backend
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/backend-service:${IMAGE_TAG}
      
      - name: Update K8s manifest
        uses: ./.github/actions/update-k8s-manifest
        with:
          service-name: 'backend'
          image-name: ${{ secrets.ACR_LOGIN_SERVER }}/backend-service
          image-tag: ${IMAGE_TAG}
